name: build dist

on:
  push:
  pull_request:

jobs:
  linux-build:
    name: build on linux
    runs-on: ubuntu-20.04
    steps:
    - name: checkout
      uses: actions/checkout@v1
      with:
        submodules: recursive
    - name: apt update
      run: |
        sudo apt-get update
    - name: set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: apt install
      run: |
        echo y | sudo apt-get install doxygen libgrpc++-dev libgrpc-dev libprotobuf-dev graphviz cmake ninja-build liblilv-dev
    - name: stupid NDK setup workaround for GitHub Actions
      run: sudo chmod 777 /usr/local/lib/android/sdk/ && mkdir -p /usr/local/lib/android/sdk/ndk
    - name: create local.properties
      run: echo "cmake.dir=/usr" > local.properties
    - name: in AAP core, workaround for https://github.com/actions/virtual-environments/issues/2228
      run: echo cmake.dir=/usr > dependencies/android-audio-plugin-framework/java/local.properties
    - name: build
      run: make
  
  osx-build:
    name: build on osx
    runs-on: macos-10.15
    steps:
    - name: checkout
      uses: actions/checkout@v1
      with:
        submodules: recursive
    - name: set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: install deps
      run: |
        brew install doxygen ninja graphviz lilv
    - name: create local.properties
      run: echo "cmake.dir=/usr/local" > local.properties
    - name: in AAP core, workaround for https://github.com/actions/virtual-environments/issues/2228
      run: echo cmake.dir=/usr/local > dependencies/android-audio-plugin-framework/java/local.properties
    - name: build
      run: make
      env:
        ANDROID_SDK_ROOT: /Users/runner/Library/Android/sdk
    - name: upload artifact
      if: success()
      uses: actions/upload-artifact@v2
      with:
        name: androidaudioplugin-lv2-debug.aar
        path: ./androidaudioplugin-lv2/build/outputs/aar/androidaudioplugin-lv2-debug.aar
    - name: upload artifact
      if: success()
      uses: actions/upload-artifact@v2
      with:
        name: aap-guitarix-debug.apk
        path: ./aap-guitarix/build/outputs/apk/debug/aap-guitarix-debug.apk
    - name: upload artifact
      if: success()
      uses: actions/upload-artifact@v2
      with:
        name: aap-mda-lv2-debug.apk
        path: ./aap-mda-lv2/build/outputs/apk/debug/aap-mda-lv2-debug.apk
    - name: upload artifact
      if: success()
      uses: actions/upload-artifact@v2
      with:
        name: aap-sfizz-debug.apk
        path: ./aap-sfizz/build/outputs/apk/debug/aap-sfizz-debug.apk
    - name: upload artifact
      if: success()
      uses: actions/upload-artifact@v2
      with:
        name: aap-fluidsynth-debug.apk
        path: ./aap-fluidsynth/build/outputs/apk/debug/aap-fluidsynth-debug.apk
