name: build dist

on:
  push:
  pull_request:

jobs:
  linux-build:
    name: build on linux
    runs-on: ubuntu-20.04
    steps:
    - name: checkout
      uses: actions/checkout@v1
      with:
        submodules: recursive
    - name: cache NDK
      uses: actions/cache@v2
      env:
        cache-name: cache-ndk
      with:
        path: /usr/local/lib/android/sdk/ndk/21.3.6528147
        key: ndk_r21d_linux
    - name: apt update
      run: |
        sudo apt-get update
    - name: set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: apt install
      run: |
        echo y | sudo apt-get install doxygen libgrpc++-dev libgrpc-dev libprotobuf-dev protobuf-compiler protobuf-compiler-grpc graphviz cmake ninja-build liblilv-dev
    - name: stupid NDK setup workaround for GitHub Actions
      run: sudo chmod 777 /usr/local/lib/android/sdk/ && mkdir -p /usr/local/lib/android/sdk/ndk
    - name: build
      run: make
    - name: upload artifact
      if: success()
      uses: actions/upload-artifact@v2
      with:
        name: androidaudioplugin-lv2-debug.aar
        path: ./androidaudioplugin-lv2/build/outputs/aar/androidaudioplugin-lv2-debug.aar
    - name: upload artifact
      if: success()
      uses: actions/upload-artifact@v2
      with:
        name: aap-mda-lv2-debug.apk
        path: ./aap-mda-lv2/build/outputs/apk/debug/aap-mda-lv2-debug.apk
  
  osx-build:
    name: build on osx
    runs-on: macos-10.15
    steps:
    - name: checkout
      uses: actions/checkout@v1
      with:
        submodules: recursive
    - name: cache NDK
      uses: actions/cache@v2
      env:
        cache-name: cache-ndk
      with:
        path: /Users/runner/Library/Android/sdk/ndk/21.3.6528147
        key: ndk_r21d_osx
    - name: set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: install deps
      run: |
        brew install doxygen ninja graphviz lilv grpc
    - name: build
      run: make
      env:
        ANDROID_SDK_ROOT: /Users/runner/Library/Android/sdk
